@extends('app')

@section('pagetitle', 'Registration Receipt')
@section('bodyclass', 'print-body')

@section('content')

    <div class="print-toolbar no-print">
        <a href="javascript:history.back()" class="btn btn-soft btn-sm"><i class="bi bi-arrow-left me-1"></i>Back</a>
        <a href="{{ route('patient.profile', ['id' => $patient->Id]) }}" class="btn btn-soft btn-sm"><i class="bi bi-person-lines-fill me-1"></i>Profile</a>
        <a href="{{ route('patient.label', ['id' => $patient->Id]) }}" class="btn btn-soft btn-sm"><i class="bi bi-upc me-1"></i>Barcode Label</a>
        <button class="btn btn-gradient btn-sm" data-print-page><i class="bi bi-printer me-1"></i>Print Receipt</button>
    </div>

    <div class="print-doc">
        <div class="doc-band"></div>

        <div class="doc-head">
            <div class="doc-brand">
                <div class="brand-icon"><i class="bi bi-activity"></i></div>
                <div>
                    <strong>I D C</strong>
                    <small>Invasive Ductal Carcinoma Diagnostic Center</small>
                </div>
            </div>
            <div class="doc-meta">
                <div class="doc-no">RECEIPT № IDC-{{ str_pad($patient->Id, 5, '0', STR_PAD_LEFT) }}</div>
                <div>Issued: {{ now()->format('d M Y · h:i A') }}</div>
                <div>Registered: {{ $patient->created_at ? $patient->created_at->format('d M Y · h:i A') : '—' }}</div>
            </div>
        </div>

        <div class="doc-title">
            <h5>Sample Registration Receipt</h5>
        </div>

        <div class="doc-section">
            <div class="sec-label"><i class="bi bi-person-vcard"></i> Patient Information</div>
            <div class="doc-grid">
                <div class="doc-field"><div class="df-label">Patient Name</div><div class="df-value">{{ $patient->Name }}</div></div>
                <div class="doc-field"><div class="df-label">Sample No</div><div class="df-value">#{{ $patient->Sampleno }}</div></div>
                <div class="doc-field"><div class="df-label">Patient ID</div><div class="df-value">IDC-{{ str_pad($patient->Id, 5, '0', STR_PAD_LEFT) }}</div></div>
                <div class="doc-field"><div class="df-label">Email</div><div class="df-value">{{ $patient->Email }}</div></div>
                <div class="doc-field"><div class="df-label">Contact No</div><div class="df-value">{{ $patient->Contactno }}</div></div>
                <div class="doc-field"><div class="df-label">Registered By (LT)</div><div class="df-value">{{ $patient->Addedby }}</div></div>
            </div>
        </div>

        <div class="doc-section">
            <div class="sec-label"><i class="bi bi-clipboard2-pulse"></i> Requested Investigation</div>
            <div class="doc-grid" style="grid-template-columns: 2fr 1fr 1fr;">
                <div class="doc-field"><div class="df-label">Examination</div><div class="df-value">Histopathology — Invasive Ductal Carcinoma (IDC) Screening</div></div>
                <div class="doc-field"><div class="df-label">Method</div><div class="df-value">AI-assisted microscopy</div></div>
                <div class="doc-field">
                    <div class="df-label">Status</div>
                    <div class="df-value">{{ $patient->treated == '1' ? 'Result Recorded' : 'In Processing' }}</div>
                </div>
            </div>
        </div>

        <div class="doc-barcode">
            <svg id="receiptBarcode"></svg>
            <div class="bc-hint">Scan for sample identification</div>
        </div>

        <div class="doc-note">
            <strong>Please note:</strong> Keep this receipt safe — the sample number is required for all inquiries.
            Your diagnostic result will be sent automatically to the registered email address.
            For queries, contact the laboratory desk and quote your sample number.
        </div>

        <div class="doc-sign">
            <div class="sig">
                <div class="sig-line"></div>
                <div class="sig-name">{{ $patient->Addedby }}</div>
                <div class="sig-role">Laboratory Technician</div>
            </div>
            <div class="sig">
                <div class="sig-line"></div>
                <div class="sig-name">Reception Desk</div>
                <div class="sig-role">Authorized Stamp</div>
            </div>
        </div>

        <div class="doc-foot">
            <span><span class="fw-white">IDC Diagnostic Center</span> · AI-assisted histopathology</span>
            <span>Generated by IDC Portal · {{ now()->format('d M Y') }}</span>
        </div>
    </div>
@endsection

@push('scripts')
    <script>
        JsBarcode('#receiptBarcode', @json($patient->Sampleno), {
            format: 'CODE128',
            width: 2.1,
            height: 64,
            margin: 0,
            displayValue: true,
            fontSize: 14,
            font: 'Plus Jakarta Sans',
            fontOptions: 'bold',
            textMargin: 6
        });
    </script>
@endpush
